In [1]:
import numpy as np
import pandas as pd

In [2]:
array = np.array([
  [2.7810836,   2.550537003,  0],
  [1.465489372, 2.362125076,  0],
  [3.396561688, 4.400293529,  0],
  [1.38807019,  1.850220317,  0],
  [3.06407232,  3.005305973,  0],
  [7.627531214, 2.759262235,  1],
  [5.332441248, 2.088626775,  1],
  [6.922596716, 1.77106367,   1],
  [8.675418651, -0.242068655, 1],
  [7.673756466, 3.508563011,  1]
]).astype(float)

column_values = ['X1', 'X2', 'Y']

df = pd.DataFrame(data = array, columns = column_values)

df

         X1        X2    Y
0  2.781084  2.550537  0.0
1  1.465489  2.362125  0.0
2  3.396562  4.400294  0.0
3  1.388070  1.850220  0.0
4  3.064072  3.005306  0.0
5  7.627531  2.759262  1.0
6  5.332441  2.088627  1.0
7  6.922597  1.771064  1.0
8  8.675419 -0.242069  1.0
9  7.673756  3.508563  1.0

In [3]:
x = df.drop(['Y'], axis = 1)
y = df['Y']

In [4]:
coef = [0] * x.shape[1]
inter = 0
predictions = [0] * len(df)

In [7]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [8]:
lr = 0.3

In [9]:
epochs = 6

In [30]:
for epoch in range(epochs):
    for i in range(len(df)):
        prediction = sigmoid(inter + coef[0]*x.loc[i,"X1"] + coef[1]*x.loc[i,"X2"])
        predictions[i] = prediction   
        inter += lr * (y.loc[i]-prediction) * prediction * (1-prediction) * 1.0
        coef[0] += lr * (y.loc[i]-prediction) * prediction * (1-prediction) * x.loc[i, "X1"]
        coef[1] += lr * (y.loc[i]-prediction) * prediction * (1-prediction) * x.loc[i, "X2"]
    print(df)
#     print(predictions)
    for i, p in enumerate(predictions):
        if (p>0.5):
            predictions[i] = 1
        else:
            predictions[i] = 0
    print(predictions)
    print()
    print()

         X1        X2    Y
0  2.781084  2.550537  0.0
1  1.465489  2.362125  0.0
2  3.396562  4.400294  0.0
3  1.388070  1.850220  0.0
4  3.064072  3.005306  0.0
5  7.627531  2.759262  1.0
6  5.332441  2.088627  1.0
7  6.922597  1.771064  1.0
8  8.675419 -0.242069  1.0
9  7.673756  3.508563  1.0
[0, 0, 0, 0, 0, 0, 0, 1, 1, 1]


         X1        X2    Y
0  2.781084  2.550537  0.0
1  1.465489  2.362125  0.0
2  3.396562  4.400294  0.0
3  1.388070  1.850220  0.0
4  3.064072  3.005306  0.0
5  7.627531  2.759262  1.0
6  5.332441  2.088627  1.0
7  6.922597  1.771064  1.0
8  8.675419 -0.242069  1.0
9  7.673756  3.508563  1.0
[1, 0, 0, 0, 0, 0, 1, 1, 1, 1]


         X1        X2    Y
0  2.781084  2.550537  0.0
1  1.465489  2.362125  0.0
2  3.396562  4.400294  0.0
3  1.388070  1.850220  0.0
4  3.064072  3.005306  0.0
5  7.627531  2.759262  1.0
6  5.332441  2.088627  1.0
7  6.922597  1.771064  1.0
8  8.675419 -0.242069  1.0
9  7.673756  3.508563  1.0
[1, 0, 0, 0, 0, 0, 1, 1, 1, 1]


         X1        X2    Y
0  2.781084  2.550537  0.0
1  1.465489  2.362125  0.0
2  3.396562  4.400294  0.0
3  1.388070  1.850220  0.0
4  3.064072  3.005306  0.0
5  7.627531  2.759262  1.0
6  5.332441  2.088627  1.0
7  6.922597  1.771064  1.0
8  8.675419 -0.242069  1.0
9  7.673756  3.508563  1.0
[1, 0, 0, 0, 0, 1, 1, 1, 1, 1]


         X1        X2    Y
0  2.781084  2.550537  0.0
1  1.465489  2.362125  0.0
2  3.396562  4.400294  0.0
3  1.388070  1.850220  0.0
4  3.064072  3.005306  0.0
5  7.627531  2.759262  1.0
6  5.332441  2.088627  1.0
7  6.922597  1.771064  1.0
8  8.675419 -0.242069  1.0
9  7.673756  3.508563  1.0
[1, 0, 0, 0, 0, 1, 1, 1, 1, 1]


         X1        X2    Y
0  2.781084  2.550537  0.0
1  1.465489  2.362125  0.0
2  3.396562  4.400294  0.0
3  1.388070  1.850220  0.0
4  3.064072  3.005306  0.0
5  7.627531  2.759262  1.0
6  5.332441  2.088627  1.0
7  6.922597  1.771064  1.0
8  8.675419 -0.242069  1.0
9  7.673756  3.508563  1.0
[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]